---

- hosts: all
  gather_facts: yes

  tasks:
  - name: print 
    debug:
      msg: |
        hostname: '{{ ansible_hostname }}'
        OS: '{{ ansible_distribution }}'
  
  - name: print user and pass
    debug:
      msg: |
        user: '{{ my_user }}'
        password: '{{ my_password }}'      